### ISSUE TITLE
Upgrade design system

### ISSUE THREAD

**Issue by maxatdetroit** [CityOfDetroit/local-services-lookup#139]
**Is your feature request related to a problem? Please describe.**

My Home Info web app is using design system version 1.0.1, and 1.0.10 was just released.

Creating this for tracking so we don't forget to upgrade and avoid painful late upgrades in the future.

**Comment by jedgar1mx** [comment]
The dependency is no longer in the list of packages. Currently the libraries are loaded via CDN on the main `index.html` file and they are running the latest version.
